apiVersion: apps/v1
kind: Deployment
metadata:
  name: schedule-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: schedule-app
  template:
    metadata:
      labels:
        app: schedule-app
    spec:
      containers:
      - name: schedule-container
        image: ttl.sh/schedule-img:8h
        imagePullPolicy: "Always"
        ports:
        - containerPort: 8001
        envFrom:

        - secretRef:
            name: schedule-secrets
        resources:
          requests:
            memory: 80Mi
            cpu: 40m
          limits:
            memory: 256Mi
            cpu: 200m

