apiVersion: v1
kind: Secret
metadata:
  name: schedule-secrets
type: Opaque
data:
  MYSQL_DATABASE: aG9yYXJpb3M=
  MYSQL_USER: eW8=
  MYSQL_PASSWORD: YWRtaW4=
  MYSQL_PORT: MzMwNg==
  API_PORT: ODAwMQ==
  SQLALCHEMY_DATABASE_URL: Y291cnNlcy1teXNxbC1zZXJ2aWNl
