apiVersion: v1
kind: Service
metadata:
  name: schedule-mysql-service
spec:
  type: ClusterIP
  selector:
    app: schedule-mysql-app
  ports:
    - port: 3306

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: schedule-mysql-statefulset
spec:
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: schedule-mysql-app
  serviceName: schedule-mysql-service
  template:
    metadata:
      labels:
        app: schedule-mysql-app
    spec:
      containers:
        - name: schedule-mysql-container
          image: mysql:8.0
          envFrom:
            - secretRef:
                name: schedule-mysql-secrets
          ports:
            - containerPort: 3306
          
          volumeMounts:
            - name: pvc
              mountPath: /data/db
              subPath: schedule-mysql-app
            # - name: mysql-initdb
            #   mountPath: /docker-entrypoint-initdb.d
            #   subPath: init.sql
      volumes:
        - name: pvc
          persistentVolumeClaim:
            claimName: schedule-mysql-pvc
        # - name: mysql-initdb
        #   configMap:
        #     name: schedule-mysql-config

---

apiVersion: v1
kind: Secret
metadata:
  name: schedule-mysql-secrets
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: YWRtaW4=
  MYSQL_DATABASE: aG9yYXJpb3M=
  MYSQL_USER: eW8=
  MYSQL_PASSWORD: YWRtaW4=
  MYSQL_PORT: MzMwNg==
