networks:
  rabbitmq:
    external: true

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword  
      MYSQL_DATABASE: enrollment_db    
      MYSQL_USER: myuser             
      MYSQL_PASSWORD: mypassword     
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 30s
      retries: 10
      start_period: 30s
    ports:
      - "3300:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - rabbitmq

  enrollment-service:
    container_name: enrollment-app
    image: enrollment-img
    ports:
      - "8002:8002"
    environment:
      - DATABASE_URL=mysql+pymysql://myuser:mypassword@db/enrollment_db
    depends_on:
      - db
    networks:
      - rabbitmq

  #rabbit-consumer:
    #build:
      #context: .
      #dockerfile: ./app/rabbit_consume/Dockerfile
    #networks:
      #- rabbitmq
volumes:
  mysql_data: