version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword  
      MYSQL_DATABASE: enrollment_db    
      MYSQL_USER: myuser             
      MYSQL_PASSWORD: mypassword     
    ports:
      - "3300:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - rabbitmq

  enrollment-service:
    build: .
    ports:
      - "6000:6000"
    environment:
      - DATABASE_URL=mysql+pymysql://myuser:mypassword@db/enrollment_db
    depends_on:
      - db
    networks:
      - rabbitmq
volumes:
  mysql_data:

networks:
  rabbitmq:
    name: rabbitmq