apiVersion: v1
kind: Secret
metadata:
  name: courses-secrets
type: Opaque
data:
  MYSQL_DATABASE: Y3Vyc29z
  MYSQL_USER: eW8=
  MYSQL_PASSWORD: YWRtaW4=
  MYSQL_PORT: MzMwNg==
  API_PORT: ODAwMA==
  SQLALCHEMY_DATABASE_URL: Y291cnNlcy1teXNxbC1zZXJ2aWNl
  RABBIT_USER: ZGVmYXVsdF91c2VyX0YyYVlXY28xZnpWV0VpT2NrbWs=
  RABBIT_PASSWORD: ekFlelM0cVJEXzgtSnItallCUDBCVE1uY25nQ3ozSnY=
  RABBIT_NAME: cmFiYml0bXFjbHVzdGVy