apiVersion: v1
kind: Service
metadata:
  name: courses-api-gateway-loadbalancer
spec:
  selector:
    app: courses-api-gateway-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8030
  type: LoadBalancer