apiVersion: v1
kind: Secret
metadata:
  name: enrollment-secrets
type: Opaque
data:
  MYSQL_DATABASE: ZW5yb2xsbWVudF9kYg==
  MYSQL_USER: bXl1c2Vy
  MYSQL_PASSWORD: bXlwYXNzd29yZA==
  MYSQL_PORT: MzMwNg==
  API_PORT: ODAwMg==
  SQLALCHEMY_DATABASE_URL: ZW5yb2xsbWVudC1teXNxbC1zZXJ2aWNl
  RABBIT_USER: ZGVmYXVsdF91c2VyX0YyYVlXY28xZnpWV0VpT2NrbWs=
  RABBIT_PASSWORD: ekFlelM0cVJEXzgtSnItallCUDBCVE1uY25nQ3ozSnY=
  RABBIT_NAME: cmFiYml0bXFjbHVzdGVy