apiVersion: v1
kind: Service
metadata:
  name: enrollment-mysql-service
spec:
  type: ClusterIP
  selector:
    app: enrollment-mysql-app
  ports:
    - port: 3306

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: enrollment-mysql-statefulset
spec:
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: enrollment-mysql-app
  serviceName: enrollment-mysql-service
  template:
    metadata:
      labels:
        app: enrollment-mysql-app
    spec:
      containers:
        - name: enrollment-mysql-container
          image: mysql:8.0
          envFrom:
            - secretRef:
                name: enrollment-mysql-secrets
          ports:
            - containerPort: 3306
          
          volumeMounts:
            - name: pvc
              mountPath: /data/db
              subPath: enrollment-mysql-app
          
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              memory: 200Mi
              cpu: 300m
      volumes:
        - name: pvc
          persistentVolumeClaim:
            claimName: enrollment-mysql-pvc

---

apiVersion: v1
kind: Secret
metadata:
  name: enrollment-mysql-secrets
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdHBhc3N3b3Jk
  MYSQL_DATABASE: ZW5yb2xsbWVudF9kYg==
  MYSQL_USER: bXl1c2Vy
  MYSQL_PASSWORD: bXlwYXNzd29yZA==
  MYSQL_PORT: MzMwNg==
