
networks:
  rabbitmq:
    name: rabbitmq

services:
  db:
    image: mysql:8.0 
    environment:
      MYSQL_DATABASE: 'cursos'
      MYSQL_USER: 'yo' 
      MYSQL_PASSWORD: 'admin' 
      MYSQL_ROOT_PASSWORD: 'admin' 
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 30s
      retries: 10
      start_period: 30s
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - rabbitmq


  api:
    build: 
      context: .
      dockerfile: ./Dockerfile  
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000 
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    networks:
      - rabbitmq

volumes:
  db_data: